sudo: false
language: python
python:
  - "3.4"
cache: apt
addons:
  apt:
    packages:
      - gfortran
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy nose matplotlib
  - pip install pep8 python-coveralls
  - pip install .
script:
  - nosetests -v --with-coverage --cover-package=pyiacsun
after_success:
  - coveralls
