sudo: false
language: python
python:
  - "3.4"
cache: apt
addons:
  apt:
    packages:
      - gfortran
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy nose matplotlib sphinx
  - pip install pep8 python-coveralls PyWavelets
  - python setup.py build_ext --inplace
#  - pip install .

env:
  global:
    - GH_REF: github.com/aasensio/pyiacsun.git
    - secure: "KWQ8/sIC2mfqOtX9iYU2Z6Hw6oEK9+yUQjVLArh5OWVhALluyWvvRdjW8aFY7EZgCJ1AubWobUrjAdxaO3CinjcUlilJXMDO57Z0etn69iIiWqExLlZWSrMIq5Epd59N28roh4hTO+xjcpR4u63Q6O8cI7YitMyVR1S6m8wiGntsMgbfN4u5GonZaY9AdbV8HzC5FDdLbqwj/51c1YK9Zw9wC9OjSS5hzz5blslJKugujK6QkvhAR39hBKAWOLKTd+TCGyk2ccl1sTP+7AKyParAINWHYw2BrkX4wuGJpYodjmoRo+xr3TNH+XZsRo+qreWR3mPQM//wVbyiXO0zv1BtwU5g9+I8qR+VEnf5alkN9KhYDR+TZ8kQcCADj7NNuz/oKyfqYxB3UpNscn0T/4g2TQ151czx0FWjDRHnsJeKEC52npGeuaH02dOj02+SzCS4HOjFDTl5o862CCyXYE70j3ndDndpsmLeHZZFrzMTqhg0X83zuen+YUqQPQIwD7knHQMKIQ89AmC9EqcRzf8qMBJhfiLABiA8CKYoN+jL9BMF20NPU5+gHKWS84BO1meDKvpdYNziRdZgFEev0OXvSxelDIZ2QRKHzjnOI5PqPpZ5by2DYQf+/zVyi+itJNbFuvCTAd86EjPStnwmL7P1jKo8o07EP0/nOSXkxbk="

script:
  - bash ./deploy_docs.sh
  - nosetests -v --with-coverage --cover-package=pyiacsun
after_success:
  - coveralls
